sudo: required

language: go

services:
    - docker
install:
    - echo "nothing to install"
script:
    - echo "nothing at all"


after_success:
    - SHA=$(git rev-parse HEAD)
    - docker --version
    - docker build -t kirandasika30/resume-server:$SHA -f Dockerfile .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - docker push kirandasika30/resume-server:$SHA
