sudo: required

language: go

services:
    - docker
install:
    - echo "nothing to install"
script:
    - echo "nothing at all"


after_success:
    - docker --version
    - docker build -t kirandasika30/res-service -f Dockerfile .
    - docker login -u $DOCKER_USERNAME --password-stdin
    - docker push kirandasika30/res-service
